# fly.toml app configuration file generated for quizlet-bot on 2025-06-01T21:25:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quizlet-bot"
primary_region = "fra"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"

  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
