# fly.toml app configuration file generated for quizlet-bot on 2025-06-01T21:25:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quizlet-bot'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
